#!/usr/bin/env node
// Renders every project in projects.json to png/<id>.png (2x) with headless Chrome,
// then rewrites the block between the cards markers in ../README.md.
//
//   node cards/build.mjs            render all cards + update README
//   node cards/build.mjs flur nafa  render only these cards + update README
//   node cards/build.mjs --preview  write .render.html only (open it to see every card)
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const DIR = dirname(fileURLToPath(import.meta.url));
const README = join(DIR, '..', 'README.md');
const RENDER = join(DIR, '.render.html');
const CHROME = process.env.CHROME || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const SIZES = { full: [880, 240], half: [430, 240] };
const START = '<!-- cards:start (generated by cards/build.mjs; edit cards/projects.json instead) -->';
const END = '<!-- cards:end -->';

const { sections } = JSON.parse(readFileSync(join(DIR, 'projects.json'), 'utf8'));
const projects = sections.flatMap(s => s.projects).filter(p => p.card !== false);
const args = process.argv.slice(2);
const previewOnly = args.includes('--preview');
const only = args.filter(a => !a.startsWith('--'));

for (const id of only) if (!projects.some(p => p.id === id)) throw new Error(`no project with id "${id}"`);
for (const p of projects) {
  if (!SIZES[p.size]) throw new Error(`${p.id}: size must be "full" or "half"`);
  if (p.shot && !existsSync(join(DIR, 'shots', p.shot))) throw new Error(`${p.id}: missing shots/${p.shot}`);
}

const esc = s => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/"/g, '&quot;');

function cardHTML(p) {
  const { bg, ink, acc } = p.theme;
  const visual = p.shot
    ? `<img src="shots/${esc(p.shot)}" style="object-position:${p.focus || '50% 50%'}" alt="">`
    : p.term
      ? `<pre class="term">${esc(p.term)}</pre>`
    : p.shelf
      ? `<div class="shelf">${p.shelf.map(s => `<span>${esc(s)}</span>`).join('')}</div>`
      : `<div class="ph"><span>${esc(p.name.replace(/^cody's /i, '')[0].toUpperCase())}</span></div>`;
  const url = p.site || (p.href ? p.href.replace('https://', '') : 'in development');
  return `<div class="card ${p.size}" id="${esc(p.id)}" style="--bg:${bg};--ink:${ink};--acc:${acc}">
  <div class="shot">${visual}</div>
  <div class="txt">${p.status === 'dev' ? '<span class="tag">in development</span>' : ''}<span class="name">${esc(p.name)}</span><span class="line">${esc(p.line)}</span><span class="url">${esc(url)}</span></div>
</div>`;
}

const page = `<!doctype html><meta charset="utf-8">
<style>
@font-face { font-family: Geist; font-weight: 400; src: url(fonts/geist-latin-400.woff2); }
@font-face { font-family: Geist; font-weight: 500; src: url(fonts/geist-latin-500.woff2); }
@font-face { font-family: Geist; font-weight: 600; src: url(fonts/geist-latin-600.woff2); }
@font-face { font-family: Geist; font-weight: 700; src: url(fonts/geist-latin-700.woff2); }
@font-face { font-family: Geist Mono; font-weight: 400; src: url(fonts/geist-mono-latin-400.woff2); }
@font-face { font-family: Geist Mono; font-weight: 500; src: url(fonts/geist-mono-latin-500.woff2); }
* { box-sizing: border-box; margin: 0; }
html, body { background: transparent; }
body { display: grid; gap: 16px; padding: 16px; justify-items: start; }
body.solo { padding: 0; }
body.solo .card:not(.on) { display: none; }

.card { position: relative; overflow: hidden; border-radius: 12px; background: var(--bg); color: var(--ink); font-family: Geist, "Helvetica Neue", Arial, sans-serif; -webkit-font-smoothing: antialiased; }
.card::after { content: ""; position: absolute; inset: 0; border-radius: inherit; box-shadow: inset 0 0 0 1px rgba(127,127,127,.2); pointer-events: none; }
.card.full { width: 880px; height: 240px; }
.card.half { width: 430px; height: 240px; }

.shot { position: absolute; overflow: hidden; background: rgba(127,127,127,.12); box-shadow: 0 0 0 1px rgba(127,127,127,.25), 0 9px 26px rgba(0,0,0,.25); }
.shot img { width: 100%; height: 100%; object-fit: cover; display: block; }
.full .shot { left: 326px; top: 23px; right: 0; bottom: 0; border-top-left-radius: 10px; }
.half .shot { left: 22px; top: 22px; right: 0; height: 122px; border-radius: 9px 0 0 9px; }

.ph { position: absolute; inset: 0; display: grid; place-items: center; background: repeating-linear-gradient(135deg, transparent 0 10px, rgba(127,127,127,.13) 10px 11px); }
.ph span { font-weight: 700; font-size: 120px; letter-spacing: -.04em; color: var(--acc); opacity: .35; }
.half .ph span { font-size: 80px; }
.term { position: absolute; inset: 0; margin: 0; padding: 22px 26px; background: rgba(0,0,0,.28); color: var(--ink); font: 12.5px/1.55 "SF Mono", Menlo, ui-monospace, monospace; white-space: pre; overflow: hidden; }
.half .term { font-size: 10px; padding: 14px 16px; }
.shelf { position: absolute; inset: 0; display: flex; flex-wrap: wrap; align-content: center; gap: 7px; padding: 14px 18px; font: 500 11px "Geist Mono", ui-monospace, monospace; }
.shelf span { border: 1px solid currentColor; border-radius: 99px; padding: 3px 9px; opacity: .8; white-space: nowrap; }

.txt { position: absolute; display: grid; align-content: start; min-width: 0; }
.tag { font: 500 11px "Geist Mono", ui-monospace, monospace; text-transform: uppercase; letter-spacing: .1em; color: var(--acc); display: flex; align-items: center; gap: 7px; }
.tag::before { content: ""; width: 7px; height: 7px; border-radius: 50%; background: currentColor; }
.name { font-weight: 650; letter-spacing: -.02em; line-height: 1.05; }
.line { opacity: .72; line-height: 1.32; }
.url { font: 400 10.5px "Geist Mono", ui-monospace, monospace; opacity: .5; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }

.full .txt { left: 30px; top: 28px; bottom: 26px; width: 274px; gap: 9px; grid-template-rows: auto auto 1fr auto; }
.full .name { font-size: 25.5px; }
.full .line { font-size: 14.5px; }
.full .url { align-self: end; }

.half .txt { left: 22px; right: 22px; bottom: 19px; gap: 4px; }
.half .tag, .half .url { display: none; }
.half .name { font-size: 21.5px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
.half .line { font-size: 13.3px; display: -webkit-box; -webkit-line-clamp: 2; -webkit-box-orient: vertical; overflow: hidden; }
</style>
<body>
${projects.map(cardHTML).join('\n')}
<script>
const id = decodeURIComponent(location.hash.slice(1));
if (id) { document.body.classList.add('solo'); document.getElementById(id)?.classList.add('on'); }
</script>
</body>`;
writeFileSync(RENDER, page);
if (previewOnly) { console.log(`preview: ${RENDER}`); process.exit(0); }

if (!existsSync(CHROME)) throw new Error(`Chrome not found at ${CHROME}; set CHROME=/path/to/chrome`);
for (const p of projects) {
  if (only.length && !only.includes(p.id)) continue;
  const [w, h] = SIZES[p.size];
  const out = join(DIR, 'png', `${p.id}.png`);
  execFileSync(CHROME, [
    '--headless=new', '--disable-gpu', '--hide-scrollbars', '--force-device-scale-factor=2',
    `--window-size=${w},${h}`, '--default-background-color=00000000', '--virtual-time-budget=3000',
    `--screenshot=${out}`, `${pathToFileURL(RENDER).href}#${encodeURIComponent(p.id)}`,
  ], { stdio: 'ignore' });
  console.log(`rendered ${relative(process.cwd(), out)}`);
}

// README block: consecutive half cards pair up on one row
const rel = p => `cards/png/${p.id}.png`;
const img = p => `<img src="${rel(p)}" width="${p.size === 'half' ? '49%' : '100%'}" alt="${esc(p.name)}: ${esc(p.line)}">`;
const linked = p => (p.href ? `<a href="${p.href}">${img(p)}</a>` : img(p));
const block = sections.map(s => {
  const rows = [];
  for (let i = 0; i < s.projects.length;) {
    const p = s.projects[i], q = s.projects[i + 1];
    if (p.card === false) { rows.push(`- **${p.href ? `[${p.name}](${p.href})` : p.name}**: ${p.line}`); i++; }
    else if (p.size === 'half' && q?.size === 'half') { rows.push(`<p>\n  ${linked(p)}\n  ${linked(q)}\n</p>`); i += 2; }
    else { rows.push(`<p>${linked(p)}</p>`); i++; }
  }
  return [s.heading, s.note && `_${s.note}_`, rows.join('\n')].filter(Boolean).join('\n\n');
}).join('\n\n');

const readme = readFileSync(README, 'utf8');
const a = readme.indexOf(START), b = readme.indexOf(END);
if (a < 0 || b < a) throw new Error(`README.md needs the markers:\n${START}\n${END}`);
writeFileSync(README, readme.slice(0, a + START.length) + `\n${block}\n` + readme.slice(b));
console.log('updated README.md');
